/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "DAMailboxFetchMessageRequest.h"

#import "MFDAMailAccountRequest.h"

@class MFDAMessageStore, Message, MimePart;

@interface _MFDAMessageStoreFetchRequest : DAMailboxFetchMessageRequest <MFDAMailAccountRequest>
{
    id <MFRequestQueueResponseConsumer><DAMailAccountStreamConsumerFactory> consumer;
    MFDAMessageStore *store;
    Message *message;
    MimePart *part;
    int format;
    BOOL partial;
}

- (unsigned long long)generationNumber;
- (BOOL)shouldSend;
- (id)deferredOperation;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;

@end

